-- =============================================================================
-- Step 2: Create the directory-table stream and scheduled task
-- =============================================================================
-- PLACEHOLDERS:
--   {{STREAM_DATABASE}}, {{STREAM_SCHEMA}}, {{STREAM_NAME}}
--   {{LANDING_DATABASE}}, {{LANDING_SCHEMA}}, {{LANDING_STAGE}}
--   {{TASK_DATABASE}}, {{TASK_SCHEMA}}, {{TASK_NAME}}, {{WAREHOUSE}}, {{SCHEDULE}}
--   {{PROCEDURE_DATABASE}}, {{PROCEDURE_SCHEMA}}, {{PROCEDURE_NAME}}
--   {{ENCRYPTED_DATABASE}}, {{ENCRYPTED_SCHEMA}}, {{ENCRYPTED_STAGE}}

CREATE OR REPLACE STREAM {{STREAM_DATABASE}}.{{STREAM_SCHEMA}}.{{STREAM_NAME}}
  ON STAGE {{LANDING_DATABASE}}.{{LANDING_SCHEMA}}.{{LANDING_STAGE}};

CREATE OR REPLACE TASK {{TASK_DATABASE}}.{{TASK_SCHEMA}}.{{TASK_NAME}}
  WAREHOUSE = {{WAREHOUSE}}
  SCHEDULE = '{{SCHEDULE}}'
  WHEN SYSTEM$STREAM_HAS_DATA('{{STREAM_DATABASE}}.{{STREAM_SCHEMA}}.{{STREAM_NAME}}')
AS
  CALL {{PROCEDURE_DATABASE}}.{{PROCEDURE_SCHEMA}}.{{PROCEDURE_NAME}}(
    'incremental',
    '{{LANDING_DATABASE}}.{{LANDING_SCHEMA}}.{{LANDING_STAGE}}',
    '{{ENCRYPTED_DATABASE}}.{{ENCRYPTED_SCHEMA}}.{{ENCRYPTED_STAGE}}',
    '{{STREAM_DATABASE}}.{{STREAM_SCHEMA}}.{{STREAM_NAME}}'
  );

ALTER TASK {{TASK_DATABASE}}.{{TASK_SCHEMA}}.{{TASK_NAME}} RESUME;
