-- =============================================================================
-- Step 0: Secret, Network Rule, Integration, Stage, Target Table
-- =============================================================================
-- PLACEHOLDERS: {{SECRET_*}}, {{NULLAFI_API_KEY}}, {{NETWORK_RULE_*}},
--   {{NULLAFI_HOSTNAME}}, {{INTEGRATION_NAME}}, {{LANDING_*}}, {{TABLE_*}}

USE ROLE SYSADMIN;
CREATE OR REPLACE SECRET {{SECRET_DATABASE}}.{{SECRET_SCHEMA}}.{{SECRET_NAME}}
  TYPE = GENERIC_STRING SECRET_STRING = '{{NULLAFI_API_KEY}}';

USE ROLE ACCOUNTADMIN;
CREATE OR REPLACE NETWORK RULE {{NETWORK_RULE_DB}}.{{NETWORK_RULE_SCHEMA}}.{{NETWORK_RULE_NAME}}
  MODE = EGRESS TYPE = HOST_PORT VALUE_LIST = ('{{NULLAFI_HOSTNAME}}');
CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION {{INTEGRATION_NAME}}
  ALLOWED_NETWORK_RULES = ({{NETWORK_RULE_DB}}.{{NETWORK_RULE_SCHEMA}}.{{NETWORK_RULE_NAME}})
  ALLOWED_AUTHENTICATION_SECRETS = ({{SECRET_DATABASE}}.{{SECRET_SCHEMA}}.{{SECRET_NAME}})
  ENABLED = TRUE;

-- Stage MUST use SNOWFLAKE_SSE
CREATE STAGE IF NOT EXISTS {{LANDING_DATABASE}}.{{LANDING_SCHEMA}}.{{LANDING_STAGE}}
  DIRECTORY = (ENABLE = TRUE) ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

CREATE TABLE IF NOT EXISTS {{TABLE_DATABASE}}.{{TABLE_SCHEMA}}.{{TARGET_TABLE}} (
  FILE_NAME VARCHAR, FILE_FORMAT VARCHAR, MASKED_CONTENT VARCHAR,
  LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
