-- =============================================================================
-- Step 3: Stream + task for incremental image processing
-- =============================================================================

CREATE OR REPLACE STREAM POS.PUBLIC.NULLAFI_LANDING_STREAM_IMG
  ON STAGE POS.PUBLIC.NULLAFI_LANDING_STAGE;

CREATE OR REPLACE TASK POS.PUBLIC.NULLAFI_PARSE_EXTRACT_TASK
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = '1 MINUTE'
  WHEN SYSTEM$STREAM_HAS_DATA('POS.PUBLIC.NULLAFI_LANDING_STREAM_IMG')
AS
  CALL POS.PUBLIC.NULLAFI_PARSE_EXTRACT_IMAGES(
    'incremental',
    'POS.PUBLIC.NULLAFI_LANDING_STAGE',
    'POS.PUBLIC.NULLAFI_IMAGE_TEXT_MASKED',
    'POS.PUBLIC.NULLAFI_LANDING_STREAM_IMG'
  );

ALTER TASK POS.PUBLIC.NULLAFI_PARSE_EXTRACT_TASK RESUME;
