-- =============================================================================
-- Step 3: Stream + task for incremental loading
-- =============================================================================

CREATE OR REPLACE STREAM POS.PUBLIC.NULLAFI_LANDING_STREAM_TBL
  ON STAGE POS.PUBLIC.NULLAFI_LANDING_STAGE;

CREATE OR REPLACE TASK POS.PUBLIC.NULLAFI_FILES_TO_TABLE_TASK
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = '1 MINUTE'
  WHEN SYSTEM$STREAM_HAS_DATA('POS.PUBLIC.NULLAFI_LANDING_STREAM_TBL')
AS
  CALL POS.PUBLIC.NULLAFI_ENCRYPT_FILES_TO_TABLE(
    'incremental',
    'POS.PUBLIC.NULLAFI_LANDING_STAGE',
    'POS.PUBLIC.NULLAFI_MASKED_FILES',
    'POS.PUBLIC.NULLAFI_LANDING_STREAM_TBL'
  );

ALTER TASK POS.PUBLIC.NULLAFI_FILES_TO_TABLE_TASK RESUME;
