-- Step 1: Create network rule and external access integration
-- This allows the stored procedure to make HTTPS calls to the Nullafi API

CREATE OR REPLACE NETWORK RULE POS.PUBLIC.NULLAFI_API_NETWORK_RULE
  MODE = EGRESS
  TYPE = HOST_PORT
  VALUE_LIST = ('test2.broknus.com');

CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION NULLAFI_API_ACCESS
  ALLOWED_NETWORK_RULES = (POS.PUBLIC.NULLAFI_API_NETWORK_RULE)
  ALLOWED_AUTHENTICATION_SECRETS = (POS.PUBLIC.NULLAFI_API_KEY_SECRET)
  ENABLED = TRUE;
